---
abstract: 'Yet-another argument processor, designed to provide a standard method for parsing constructor arguments'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-YAARG
provides:
  Config::YAARG:
    file: lib/Config/YAARG.pm
    version: 0.02
requires:
  TAP::Harness: 0
version: 0.02
